import {
	useDeletePlannerAircraft,
	useGetAllPlannerAircraft,
	usePostPlannerAircraft,
	useUpdatePlannerAircraft,
} from './PlannerAirportMaster/PlannerAircraftAirportMaster';
import {
	useDeletePlannerAirline,
	useGetAllPlannerAirline,
	usePostPlannerAirline,
	useUpdatePlannerAirline,
	useUploadCSVPlannerAirline,
} from './PlannerAirportMaster/PlannerAirlineAirportMaster';
import {
	useGetAllTimelineData,
	useGetTimelineGroupData,
	useRunRuleEngine,
	useUpdateResourceAllocation,
} from './ResourceAllocationServices/ResourceAllocationServices';
import {
	useGetAllCdmArrivalDeparture,
	useGetAllCdmTurnAround,
	useUpdateCdmTurnAround,
	useUpdateCdmTypes,
} from './cdm/cdmServices';

import { useDummyApi } from './dummyApi/dummyApi';
import {
	usePostFidsResource,
	useBaggageBeltDropdown,
	useCheckInDropdown,
	useUpdateFidsResource,
	useTerminalDropdown,
	useGetAllFidsResources,
	useDeleteFidsResource,
} from './fids/fidsResources';

import {
	useGlobalAirport,
	useUploadCSVAircraftType,
	useGlobalCountries,
	useGetGlobalAirport,
	usePostGlobalAirport,
	usePatchGlobalAirport,
	useDeleteGlobalAirport,
	useGlobalAirportDropdown,
	useGetGlobalAirline,
	usePostGlobalAirline,
	usePatchGlobalAirline,
	useDeleteGlobalAirline,
	useGlobalAirlineDropdown,
	useGetGlobalAircraftType,
	usePostGlobalAircraftType,
	usePatchGlobalAircraftType,
	useDeleteGlobalAircraftType,
	useGlobalAircraftTypeDropdown,
	useGetGlobalAircraftRegistration,
	usePostGlobalAircraftRegistration,
	usePatchGlobalAircraftRegistration,
	useDeleteGlobalAircraftRegistration,
	useCountriesDropdown,
	useUploadCSVAirport,
	useUploadCSVGlobalAircraftType,
	useUploadCSVGlobalAirline,
	useUploadCSVGlobalAirport,
} from './globalMasters/globalMaster';
import { useGetAllNotification, useUpdateNotification } from './notification/notificationServices';

export {
	useDummyApi,
	useGetAllTimelineData,
	useGetTimelineGroupData,
	useGlobalAirport,
	useUploadCSVAircraftType,
	useGlobalCountries,
	useGetGlobalAirport,
	usePostGlobalAirport,
	usePatchGlobalAirport,
	useDeleteGlobalAirport,
	useGlobalAirportDropdown,
	useGetGlobalAirline,
	usePostGlobalAirline,
	usePatchGlobalAirline,
	useDeleteGlobalAirline,
	useGlobalAirlineDropdown,
	useGetGlobalAircraftType,
	usePostGlobalAircraftType,
	usePatchGlobalAircraftType,
	useDeleteGlobalAircraftType,
	useGlobalAircraftTypeDropdown,
	useGetGlobalAircraftRegistration,
	usePostGlobalAircraftRegistration,
	usePatchGlobalAircraftRegistration,
	useDeleteGlobalAircraftRegistration,
	useCountriesDropdown,
	useGetAllPlannerAircraft,
	useGetAllPlannerAirline,
	usePostPlannerAirline,
	usePostPlannerAircraft,
	useDeletePlannerAircraft,
	useDeletePlannerAirline,
	useUpdatePlannerAircraft,
	useUpdatePlannerAirline,
	useUpdateResourceAllocation,
	useUploadCSVPlannerAirline,
	useUploadCSVAirport,
	useUploadCSVGlobalAircraftType,
	useUploadCSVGlobalAirline,
	useUploadCSVGlobalAirport,
	useGetAllCdmArrivalDeparture,
	useUpdateCdmTypes,
	useUpdateCdmTurnAround,
	useGetAllCdmTurnAround,
	useBaggageBeltDropdown,
	useCheckInDropdown,
	useTerminalDropdown,
	usePostFidsResource,
	useGetAllFidsResources,
	useDeleteFidsResource,
	useUpdateFidsResource,
	useRunRuleEngine,
	useGetAllNotification,
	useUpdateNotification,
};
