export const IT_ADMIN = 'IT Admin';
export const PLANNER = 'Planner';
export const DAILY_OPS = 'daily Ops';
export const VENDOR = 'Vendor';
export const ACCESS_MANAGER = 'accessmanager';
export const SECURITY_OFFICER = 'Security Officer';
export const CDM = 'Cdm';
export const FIDS = 'Fids Manager';
export const AIRLINE_FIDS = 'Airline Crew';
