export let Pathname = {
	LOGIN: '/login',
	NAVBAR: '/nav',
	USERACCESS: '/user-access',
	GLOBALMASTERS: '/global-masters',
	AIRPORTMASTERS: '/airport-masters',
	DASHBOARD: '/dashboard',
	DASHBOARD_ORDERS: '/dashboard/orders',
	DASHBOARD_TRANSACTIONS: '/dashboard/transactions',
	COMPONENTS: '/components',
	PLANAIRPORTMASTER: '/plan-airport-masters',
	PLAN: '/plans',
	SECURITY_OFFICER: '/security-officer',
	404: '/404',
	CDM: '/cdm',
	VENDOR: '/vendor',
};
